version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "5000"
    ports:
      - 5000:5000
    volumes:
      - web-data:/usr/src/app/static
    env_file: 
      - .env
    command: uwsgi --socket 0.0.0.0:5000 --protocol=http -w app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:web

volumes:
  web-data:
